info:
  namespace: terix
huds:
  ability_bar_0: &ability_bar
    enabled: true
    show:
      auto: false
    type: CUSTOM
    x_position_pixels: 90
  ability_bar_1: *ability_bar
  ability_bar_2: *ability_bar
  ability_bar_3: *ability_bar
  ability_bar_4: *ability_bar
  ability_bar_5: *ability_bar

