@file:Suppress("unused")
@file:JvmName("Path")
package me.racci.sylphia.enums

enum class Path(val path: String,
                val type: ValueType,
                val optional: Boolean = false) {
    NAME("Identity.Name", ValueType.STRING),
    COLOUR("Identity.Colour", ValueType.STRING),
    HURT("Sound.Hurt", ValueType.SOUND),
    DEATH("Sound.Death", ValueType.SOUND),
    REQUIRED("Permissions.Required", ValueType.LIST, true),
    GIVEN("Permissions.Given", ValueType.LIST, true),
    DAY_TITLE("TimeMessage.Day.Title", ValueType.STRING, true),
    DAY_SUBTITLE("TimeMessages.Day.Subtitle", ValueType.STRING, true),
    NIGHT_TITLE("TimeMessage.Night.Title", ValueType.STRING, true),
    NIGHT_SUBTITLE("TimeMessages.Night.Subtitle", ValueType.STRING, true),
    GENERAL_ENABLE("Effects.Enabled", ValueType.BOOLEAN),
    TIME_ENABLE("Effects.Time", ValueType.BOOLEAN),
    LIQUID_ENABLE("Effects.Liquid", ValueType.BOOLEAN),
    DIMENSION_ENABLE("Effects.Dimension", ValueType.BOOLEAN),
    GENERAL_EFFECTS("Effects.General.Effects", ValueType.EFFECT, true),
    GENERAL_ATTRIBUTES("Effects.General.Attributes", ValueType.ATTRIBUTE, true),
    DAY_EFFECTS("Effects.Day.Effects", ValueType.EFFECT, true),
    DAY_ATTRIBUTES("Effects.Day.Attributes", ValueType.ATTRIBUTE, true),
    NIGHT_EFFECTS("Effects.Night.Effects", ValueType.EFFECT, true),
    NIGHT_ATTRIBUTES("Effects.Night.Attributes", ValueType.ATTRIBUTE, true),
    WATER_EFFECTS("Effects.Water.Effects", ValueType.EFFECT, true),
    WATER_ATTRIBUTES("Effects.Water.Attributes", ValueType.ATTRIBUTE, true),
    LAVA_EFFECTS("Effects.Lava.Effects", ValueType.EFFECT, true),
    LAVA_ATTRIBUTES("Effects.Lava.Attributes", ValueType.ATTRIBUTE, true),
    OVERWORLD_EFFECTS("Effects.Overworld.Effects", ValueType.EFFECT, true),
    OVERWORLD_ATTRIBUTES("Effects.Overworld.Attributes", ValueType.ATTRIBUTE, true),
    NETHER_EFFECTS("Effects.Nether.Effects", ValueType.EFFECT, true),
    NETHER_ATTRIBUTES("Effects.Nether.Attributes", ValueType.ATTRIBUTE, true),
    END_EFFECTS("Effects.End.Effects", ValueType.EFFECT, true),
    END_ATTRIBUTES("Effects.End.Attributes", ValueType.ATTRIBUTE, true),
    SLOWFALLING("Effects.Special.Slow-falling", ValueType.BOOLEAN),
    NIGHTVISION("Effects.Special.Night-vision", ValueType.BOOLEAN),
    JUMPBOOST("Effects.Special.Jump-boost", ValueType.INT),
    DAMAGE_ENABLE("Damage.Enabled", ValueType.BOOLEAN),
    SUN_ENABLE("Damage.Sun", ValueType.BOOLEAN),
    FALL_ENABLE("Damage.Fall", ValueType.BOOLEAN),
    RAIN_ENABLE("Damage.Rain", ValueType.BOOLEAN),
    WATER_ENABLE("Damage.Water", ValueType.BOOLEAN),
    LAVA_ENABLE("Damage.Lava", ValueType.BOOLEAN),
    SUN_AMOUNT("Damage.Amounts.Sun", ValueType.INT),
    FALL_AMOUNT("Damage.Amounts.Fall", ValueType.INT),
    RAIN_AMOUNT("Damage.Amounts.Rain", ValueType.INT),
    WATER_AMOUNT("Damage.Amounts.Water", ValueType.INT),
    LAVA_AMOUNT("Damage.Amounts.Lava", ValueType.INT),
    GUI_SLOT("GUI.Item.Slot", ValueType.INT),
    GUI_SKULL("GUI.Item.Skull", ValueType.STRING, true),
    GUI_MATERIAL("GUI.Item.Material", ValueType.MATERIAL, true),
    GUI_ENCHANTED("GUI.Item.Enchanted", ValueType.BOOLEAN),
    GUI_LORE_DESCRIPTION("GUI.Lore.Description", ValueType.LIST, true),
    GUI_LORE_PASSIVES("GUI.Lore.Passives", ValueType.LIST, true),
    GUI_LORE_ABILITIES("GUI.Lore.Abilities", ValueType.LIST, true),
    GUI_LORE_DEBUFFS("GUI.Lore.Debuffs", ValueType.LIST, true);
}