pre_bump_hooks = [
    "bash -c \"scripts/pre-bump.sh {{latest}} {{version}}\"",
]
post_bump_hooks = [
    "bash -c \"scripts/post-bump.sh {{latest}} {{version}} {{version+patch-SNAPSHOT}}\"",
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Terix"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]
