package dev.racci.terix.api.origins.enums

enum class KeyBinding {
    DOUBLE_OFFHAND,
    DOUBLE_SNEAK,
    DOUBLE_RIGHT_CLICK,
    DOUBLE_LEFT_CLICK,

    SINGLE_OFFHAND,
    SINGLE_SNEAK,
    SINGLE_RIGHT_CLICK,
    SINGLE_LEFT_CLICK,

    SNEAK_OFFHAND,
    SNEAK_RIGHT_CLICK,
    SNEAK_LEFT_CLICK,

    SNEAK_DOUBLE_OFFHAND,
    SNEAK_DOUBLE_RIGHT_CLICK,
    SNEAK_DOUBLE_LEFT_CLICK,
}
