name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, edited ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - id: version
        run: |
          version="$(sed -n -e 's/version=//p' gradle.properties)"
          echo "::set-output name=version::$version"

      - name: Build
        run: ./gradlew quickBuild -Pversion=${{ steps.version.outputs.version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Minix-${{ steps.version.outputs.version }}
          path: |
            build/libs/Terix-${{ steps.version.outputs.version }}.jar
            **/build/libs/Terix-*-*-sources.jar
          if-no-files-found: error

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Test
        run: ./gradlew clean test
